version: '3'

services:
  control-node:
    build: .
    container_name: control-node
    networks:
      vagrant_net:
        ipv4_address: 192.168.56.11
    volumes:
      - .:/mnt/synced_folder
      - ./ansible:/ansible  # Volume para ansible
    ports:
      - "2222:22"
    command: /usr/sbin/sshd -D

  app01:
    build: .
    container_name: app01
    networks:
      vagrant_net:
        ipv4_address: 192.168.56.12
    ports:
      - "2223:22"
    command: /usr/sbin/sshd -D

  db01:
    build: .
    container_name: db01
    networks:
      vagrant_net:
        ipv4_address: 192.168.56.13
    ports:
      - "2224:22"
    command: /usr/sbin/sshd -D

networks:
  vagrant_net:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.56.0/24
